pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Dev') {
      steps {
       echo 'Staging Env for Dev'
      }
      
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
