pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Dev Stage'){
            steps{
                script{
                    sh '''
                    echo 'Deployed the Changes in Dev Env'
         }
                }           '''
  }
}

